name: Example workflow
on:
  push:
    branches:
      - main

jobs:
  first:
    name: First job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Hello world
        run: echo "Hello world!"
  second:
    name: Second job
    needs: first
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Hello again
        run: echo "Hello again!"
